Extract the Orange Color of the Image and plot that

In [1]:
# Importing Image from PIL package
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import numpy as np
import os
import pandas as pd

In [126]:
def load_image(image_path):
    im = Image.open(image_path)
    im =im.resize((256,256))
    crop_box = (100, 100, 150, 150)
    img_cropped = im.crop(crop_box)
    return [img_cropped, im]

def show_image(image):
    img_resized = np.array(image)
    plt.grid()
    plt.imshow(img_resized)
    plt.show()

def color(image):
    redness = []
    for i in range(0,image.size[0]):
        for j in range(0,image.size[1]):
            if image.getpixel((i,j))[0] in range(180,255) and image.getpixel((i,j))[1] in range(100,165) and image.getpixel((i,j))[2] in range(0,50):
                redness.append((image.getpixel((i,j))[0] + image.getpixel((i,j))[1] + image.getpixel((i,j))[2])/3)

    avg_redness = sum(redness) / (len(redness)+1)
    return avg_redness
def files(image_dir,image_files):
    temp = []
    for image_file in image_files:
        # Construct the full image path
        image_path = os.path.join(image_dir, image_file)
        img = load_image(image_path)
        temp.append(color(img[1]))
    return max(temp) #specify operation to be performed on the 3 images color values
    # return (((sum(temp)/len(temp))/255)*100)

In [127]:
color0 = []
color1 = []
color2 = []
color3 = []
color4 = []
color5 = []
color6 = []
l = [color0,color1,color2,color3,color4,color5,color6]
s = [image_files0,image_files1,image_files2,image_files3,image_files4,image_files5,image_files6]

In [152]:
image_dir = R'D:\sohamSir\image_analysis_and_color_estimation\ImageAnalysis\data\raw\RGB Compatible Quality\250 ug RGB'
image_files = os.listdir(image_dir)
image_files1 = image_files[3:6]
image_files0 = image_files[0:3]
image_files2 = image_files[6:9]
image_files3 = image_files[9:12]
image_files4 = image_files[12:15]
image_files5 = image_files[15:18]
image_files6 = image_files[18:21]

# image_files0 = [image_files0[2]]
# image_files1 = [image_files1[2]]
# image_files2 = [image_files2[2]]
# image_files3 = [image_files3[2]]
# image_files4 = [image_files4[2]]
# image_files5 = [image_files5[2]]
# image_files6 = [image_files6[2]]

for i in range(0,7):
    l[i].append(files(image_dir, s[i]))

In [153]:
blue_color_list = pd.DataFrame({
    't0': color0,
    't1': color1,
    't2': color2,
    't3': color3,
    't4': color4,
    't5': color5,
    't6': color6
})

In [63]:
blue_color_list.to_csv('min_redness_in_3.csv', index=False)

In [154]:
blue_color_list

,t0,t1,t2,t3,t4,t5,t6
0,111.481288,0.000000,107.757576,109.974026,110.432387,111.214929,112.082687
1,0.000000,0.000000,0.000000,110.821012,110.821012,111.031546,111.292683
2,112.935673,0.000000,0.000000,0.000000,52.833333,0.000000,95.375000
3,117.873737,108.818182,103.396465,108.905983,107.526936,107.268007,109.005979
4,117.426587,0.000000,106.803922,102.575556,106.797761,106.131391,107.061720
5,111.388889,0.000000,92.291667,103.013333,108.258216,108.502630,110.027360
6,109.525000,112.163265,106.576132,0.000000,107.115152,107.164179,109.518412
7,0.000000,0.000000,109.803793,110.490004,109.803670,106.676056,100.819428
8,0.000000,0.000000,0.000000,101.178571,100.923497,99.190476,78.750000
9,0.000000,0.000000,96.083333,99.597701,99.595238,103.669811,103.811377
10,0.000000,101.566667,108.620098,54.166667,67.111111,48.833333,103.946394
11,0.000000,0.000000,96.696970,108.498106,109.795337,109.022067,96.844444
12,0.000000,0.000000,0.000000,97.812500,104.776224,109.761029,105.631206
13,0.000000,0.000000,0.000000,109.206751,103.333333,108.627385,109.225668
14,0.000000,0.000000,0.000000,97.153846,99.413793,84.250000,107.642857
15,0.000000,0.000000,0.000000,97.878788,109.469333,108.686084,104.588435
16,0.000000,0.000000,0.000000,110.491968,106.949275,112.652330,108.182004
17,0.000000,0.000000,107.654321,106.896296,106.136704,109.813140,106.181333
18,0.000000,0.000000,0.000000,0.000000,108.134615,108.519608,103.398281
19,0.000000,0.000000,0.000000,104.913043,107.567568,0.000000,51.666667
20,97.259259,0.000000,0.000000,72.000000,107.420290,106.235294,109.351351
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,104.648148,107.880952,106.797619,99.185185,108.566667,0.000000,0.000000
24,0.000000,0.000000,110.568966,99.305556,113.281116,107.947368,89.733333